---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: governance-policy-framework-addon-auth
subjects:
- kind: ServiceAccount
  name: governance-policy-framework-addon
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: governance-policy-framework-addon-auth
  apiGroup: rbac.authorization.k8s.io
