---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: governance-policy-framework-addon-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: governance-policy-framework-addon-metrics-reader
subjects:
- kind: ServiceAccount
  name: governance-policy-framework-addon
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: governance-policy-framework-addon-metrics-reader
  apiGroup: rbac.authorization.k8s.io
